name: Build

on:
  push:
    branches:
    - macos
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    env:
      LIBTOOL: glibtool
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ${{ env.HOME }}/Library/Caches/Homebrew
        key: ${{ runner.os }}-homebrew-caches-v1
    - run: brew install knazarov/qemu-virgl/libangle knazarov/qemu-virgl/libepoxy-angle knazarov/qemu-virgl/virglrenderer libtool meson ninja pkg-config glib gnutls jpeg libpng libssh libusb lzo ncurses nettle pixman snappy vde
    - run: brew cleanup
    - run: |
        sh -c "./configure --prefix=/opt/qemu-virgl \
          --disable-guest-agent --target-list x86_64-softmmu --enable-vde --extra-cflags=-DNCURSES_WIDECHAR=1 \
          --extra-cflags=-I/usr/local/opt/libangle/include --extra-cflags=-I/usr/local/opt/libepoxy-angle/include --extra-cflags=-I/usr/local/opt/virglrenderer/include \
          --extra-cflags=-L/usr/local/opt/libangle/lib --extra-cflags=-L/usr/local/opt/libepoxy-angle/lib --extra-cflags=-L/usr/local/opt/virglrenderer/lib \
          --disable-sdl --disable-gtk --enable-cocoa"
    - run: make -j3 install
    - uses: actions/upload-artifact@v2
      with:
        name: qemu-x86_64
        path: /opt/qemu-virgl